forms_and_validation:
    resource: "@FormsAndValidationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

lesons_bundle:
    resource: "@DIAndUnitTestsBundle/Resources/config/routing.yml"
    prefix:   /