Lessons\FormsAndValidationBundle\Entity\RequestContact:
    properties:
        name:
            - NotBlank: ~
        gender:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        message:
            - NotBlank: ~
        needAnswer:
            - NotBlank: ~