<?php

namespace Lessons\FormsAndValidationBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RequestContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestContactRepository extends EntityRepository
{
}
